export const SET_SUCCESS_ALERT = "SET_SUCCESS_ALERT";
export const SET_ERROR_ALERT = "SET_ERROR_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const GET_PAY_DATES = "GET_PAY_DATES";

export const GET_DATA_BY_DATE = "GET_DATA_BY_DATE";
export const GET_DATA_BY_ID = "GET_DATA_BY_ID";
export const GET_ALL_DATA = "GET_ALL_DATA";
export const DELETE_DATA_BY_DATE = "DELETE_DATA_BY_DATE";
export const DELETE_DATA_BY_ID = "DELETE_DATA_BY_ID";
export const SAVE_NEW_RECORD = "SAVE_NEW_RECORD";

export const SAVE_NEW_ASSOCIATE = "SAVE_NEW_ASSOCIATE";
export const DELETE_ASSOCIATE_BY_ID = "DELETE_ASSOCIATE_BY_ID";
export const GET_ALL_ASSOCIATES = "GET_ALL_ASSOCIATES";
export const GET_ASSOCIATE_BY_ID = "GET_ASSOCIATE_BY_ID";
export const UPDATE_ASSOCIATE = "UPDATE_ASSOCIATE";

