import moment from 'moment';
export const initialState = {
    ID: '',
    FIRSTNAME: '',
    LASTNAME: '',
    WRKD_FLG: 'N',
    HRS_VER_FLG: 'N',
    BNS_FLG: 'N',
    TIMESHEET_FLG: 'N',
    PICKUP_PAY_FLG: 'N',
    ADJ_FLG: 'N',
    ADJUSTMENT: '',
    SP_RATE: '',
    NOTES: '',
    REG_HRS: '',
    SCH_HRS: '',
    UNVH: '',
    VRF_HRS: '',
    TS_HRS: '',
    SUP: '',
    SDP: '',
    BNS_HRS: '',
    BNS_RATE: '',
    BNS_HRS_B: '',
    BNS_RATE_B: '',
    BNS_HR_C: '',
    BNS_RATE_C: '',
    BNS_HR_D: '',
    BNS_RATE_D: '',
    PAYDATE: '',
    UPDATED: moment().format(),
}

export const payrollDataMapping = (payrollData) => {
    return {
        ID: payrollData.ID,
        FIRSTNAME: payrollData.FIRSTNAME,
        LASTNAME: payrollData.LASTNAME,
        WRKD_FLG: payrollData.WRKD_FLG,
        HRS_VER_FLG: payrollData.HRS_VER_FLG,
        BNS_FLG: payrollData.BNS_FLG,
        TIMESHEET_FLG: payrollData.TIMESHEET_FLG,
        PICKUP_PAY_FLG: payrollData.PICKUP_PAY_FLG,
        ADJ_FLG: payrollData.ADJ_FLG,
        ADJUSTMENT: payrollData.ADJUSTMENT,
        SP_RATE: payrollData.SP_RATE,
        NOTES: payrollData.NOTES,
        REG_HRS: payrollData.REG_HRS,
        SCH_HRS: payrollData.SCH_HRS,
        UNVH: payrollData.UNVH,
        VRF_HRS: payrollData.VRF_HRS,
        TS_HRS: payrollData.TS_HRS,
        SUP: payrollData.SUP,
        SDP: payrollData.SDP,
        BNS_HRS: payrollData.BNS_HRS,
        BNS_RATE: payrollData.BNS_RATE,
        BNS_HRS_B: payrollData.BNS_HRS_B,
        BNS_RATE_B: payrollData.BNS_RATE_B,
        BNS_HR_C: payrollData.BNS_HR_C,
        BNS_RATE_C: payrollData.BNS_RATE_C,
        BNS_HR_D: payrollData.BNS_HR_D,
        BNS_RATE_D: payrollData.BNS_RATE_D,
        PAYDATE: payrollData.PA,
    }
}

export const dateInitialState = {
    NEWPAYDATE: '',
    UPDATED: moment().format()
}

